<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="0.207">
  <testcase classname="__main__.qa_error_distance" name="test_001_t" time="0.2072">
    <failure type="exceptions.AssertionError">2 != 1.4142135381698608 within 6 places
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/rich/Desktop/vlp_repos/gr-vlp/python/qa_error_distance.py", line 52, in test_001_t
    self.assertFloatTuplesAlmostEqual (expected_result, result_data, 6)
  File "/home/rich/Desktop/repos2/target/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 90, in assertFloatTuplesAlmostEqual
    self.assertAlmostEqual (a[i], b[i], places, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 561, in assertAlmostEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
